# Generated by Django 4.2.3 on 2024-03-22 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0006_producto_descripcion_alter_producto_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(blank=True, default='El producto no tiene descripción', null=True),
        ),
    ]
